# Generated by Django 5.1.3 on 2024-12-03 05:10

import ckeditor_uploader.fields
import django.db.models.deletion
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تصویر')),
                ('title_eng', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان انگلیسی')),
                ('keyword', models.CharField(max_length=250, verbose_name='کلمه کلیدی')),
                ('variant', models.CharField(choices=[('None', 'هیچ'), ('Size', 'سایز'), ('Color', 'رنگ'), ('Size-Color', 'سایز-رنگ')], default=None, max_length=10, verbose_name='تنوع')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=product.models.upload_image_path, verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(verbose_name='تعداد')),
                ('all_sale', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='تعداد بازدید ها')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئیات محصول')),
                ('analyze', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='نقد و بررسی')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیر فعال')], max_length=50, verbose_name='وضعیت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عبارت لینک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.brand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='دسته')),
                ('favorite', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='علاقه مندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
