# Generated by Django 5.1.3 on 2024-12-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم رنگ')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='سایز')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد سایز')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='VariantsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='ویژگی')),
                ('image_id', models.IntegerField(default=0, verbose_name='تصویر')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیر فعال')], default=True, max_length=50, verbose_name='وضعیت')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variant.color', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='product.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variant.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'تنوع',
                'verbose_name_plural': 'تنوع ها',
            },
        ),
    ]
